[versions]
asm = "9.9.1"
junit = "6.0.1"
testcontainers = "2.0.3"
assertj = "3.27.3"
shadow = "9.3.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }